---
- name: Installation of webserver
  hosts: centos1
  become: yes
  tasks:
    - name: Install Apache webserver
      yum:
        name: httpd
        state: latest
      notify: restart Apache
    - name: enable Apache in the systemd
      service:
        name: httpd
        state: started
        enabled: True
  handlers:
    - name: restart Apache
      service:
        name: httpd
        state: restarted
